# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Country.create(name: "Afghanistan")
Country.create(name: "Albania")
Country.create(name: "Albania")
Country.create(name: "American Samoa")
Country.create(name: "Andorra")
Country.create(name: "Angola")
Country.create(name: "Anguilla")
Country.create(name: "Antigua and Barbuda")
Country.create(name: "Argentina")
Country.create(name: "Armenia")
Country.create(name: "Aruba")
Country.create(name: "Australia")
Country.create(name: "Austria")
Country.create(name: "Azerbaijan")
Country.create(name: "Bahamas")
Country.create(name: "Bahrain")
Country.create(name: "Bangladesh")
Country.create(name: "Barbados")
Country.create(name: "Belarus")
Country.create(name: "Belgium")
Country.create(name: "Belize")
Country.create(name: "Benin")
Country.create(name: "Bermuda")
Country.create(name: "Bhutan")
Country.create(name: "Bolivia")
Country.create(name: "Bosnia and Herzegovina")
Country.create(name: "Botswana")
Country.create(name: "Brazil")
Country.create(name: "Brunei Darussalam")
Country.create(name: "Bulgaria")
Country.create(name: "Burkina Faso")
Country.create(name: "Burundi")
Country.create(name: "Cambodia")
Country.create(name: "Cameroon")
Country.create(name: "Canada")
Country.create(name: "Cape Verde")
Country.create(name: "Cayman Islands")
Country.create(name: "Central African Republic")
Country.create(name: "Chad")
Country.create(name: "Chile")
Country.create(name: "China")
Country.create(name: "Christmas Island")
Country.create(name: "Cocos (Keeling) Islands")
Country.create(name: "Colombia")
Country.create(name: "Comoros")
Country.create(name: "Democratic Republic of the Congo (Kinshasa)")
Country.create(name: "Congo, Republic of (Brazzaville)")
Country.create(name: "Cook Islands")
Country.create(name: "Costa Rica")
Country.create(name: "Côte D'ivoire (Ivory Coast)")
Country.create(name: "Croatia")
Country.create(name: "Cuba")
Country.create(name: "Cyprus")
Country.create(name: "Czech Republic")
Country.create(name: "Denmark")
Country.create(name: "Djibouti")
Country.create(name: "Dominica")
Country.create(name: "Dominican Republic")
Country.create(name: "East Timor (Timor-Leste)")
Country.create(name: "Ecuador")
Country.create(name: "Egypt")
Country.create(name: "El Salvador")
Country.create(name: "Equatorial Guinea")
Country.create(name: "Eritrea")
Country.create(name: "Estonia")
Country.create(name: "Ethiopia")
Country.create(name: "Falkand Islands")
Country.create(name: "Faroe Islands")
Country.create(name: "Fiji")
Country.create(name: "Finland")
Country.create(name: "France")
Country.create(name: "French Guiana")
Country.create(name: "French Polynesia")
Country.create(name: "French Southern")
Country.create(name: "French Southern Territories")
Country.create(name: "Gabon")
Country.create(name: "The Gambia")
Country.create(name: "Georgia")
Country.create(name: "Germany")
Country.create(name: "Ghana")
Country.create(name: "Gibraltar")
Country.create(name: "Greece")
Country.create(name: "Greenland")
Country.create(name: "Grenada")
Country.create(name: "Guadeloupe")
Country.create(name: "Guam")
Country.create(name: "Guatemala")
Country.create(name: "Guinea")
Country.create(name: "Guinea-Bissau")
Country.create(name: "Guyana")
Country.create(name: "Haiti")
Country.create(name: "Holy See")
Country.create(name: "Honduras")
Country.create(name: "Hong Kong")
Country.create(name: "Hungary")
Country.create(name: "Iceland")
Country.create(name: "India")
Country.create(name: "Indonesia")
Country.create(name: "Iran (Islamic Republic of)")
Country.create(name: "Iraq")
Country.create(name: "Ireland")
Country.create(name: "Israel")
Country.create(name: "Italy")
Country.create(name: "Ivory Coast")
Country.create(name: "Jamaica")
Country.create(name: "Japan")
Country.create(name: "Jordan")
Country.create(name: "Kazakhstan")
Country.create(name: "Kenya")
Country.create(name: "Kiribati")
Country.create(name: "Korea, Democratic People's Rep. (North Korea)")
Country.create(name: "Korea, Republic of (South Korea)")
Country.create(name: "Kosovo")
Country.create(name: "Kuwait")
Country.create(name: "Kyrgyzstan")
Country.create(name: "Lao, People's Democratic Republic")
Country.create(name: "Latvia")
Country.create(name: "Lebanon")
Country.create(name: "Lesotho")
Country.create(name: "Liberia")
Country.create(name: "Libya")
Country.create(name: "Liechtenstein")
Country.create(name: "Lithuania")
Country.create(name: "Luxembourg")
Country.create(name: "Macau")
Country.create(name: "Madagascar")
Country.create(name: "Malawi")
Country.create(name: "Malaysia")
Country.create(name: "Maldives")
Country.create(name: "Mali")
Country.create(name: "Malta")
Country.create(name: "Marshall Islands")
Country.create(name: "Martinique")
Country.create(name: "Mauritania")
Country.create(name: "Mauritius")
Country.create(name: "Mayotte")
Country.create(name: "Mexico")
Country.create(name: "Micronesia, Federal States of")
Country.create(name: "Moldova, Republic of")
Country.create(name: "Monaco")
Country.create(name: "Mongolia")
Country.create(name: "Montenegro")
Country.create(name: "Montserrat")
Country.create(name: "Morocco")
Country.create(name: "Mozambique")
Country.create(name: "Myanmar, Burma")
Country.create(name: "Namibia")
Country.create(name: "Nauru")
Country.create(name: "Nepal")
Country.create(name: "Netherlands")
Country.create(name: "Netherlands Antilles")
Country.create(name: "New Caledonia")
Country.create(name: "New Zealand")
Country.create(name: "Nicaragua")
Country.create(name: "Niger")
Country.create(name: "Nigeria")
Country.create(name: "Niue")
Country.create(name: "North Macedonia")
Country.create(name: "Northern Mariana Islands")
Country.create(name: "Norway")
Country.create(name: "Oman")
Country.create(name: "Pakistan")
Country.create(name: "Palau")
Country.create(name: "Palestinian territories")
Country.create(name: "Panama")
Country.create(name: "Papua New Guinea")
Country.create(name: "Paraguay")
Country.create(name: "Peru")
Country.create(name: "Philippines")
Country.create(name: "Pitcairn Island")
Country.create(name: "Poland")
Country.create(name: "Portugal")
Country.create(name: "Puerto Rico")
Country.create(name: "Qatar")
Country.create(name: "Reunion Island")
Country.create(name: "Romania")
Country.create(name: "Russian Federation")
Country.create(name: "Rwanda")
Country.create(name: "Saint Kitts and Nevis")
Country.create(name: "Saint Lucia")
Country.create(name: "Saint Vincent and the Grenadines")
Country.create(name: "Samoa")
Country.create(name: "San Marino")
Country.create(name: "Sao Tome and Principe")
Country.create(name: "Saudi Arabia")
Country.create(name: "Senegal")
Country.create(name: "Serbia")
Country.create(name: "Seychelles")
Country.create(name: "Sierra Leone")
Country.create(name: "Singapore")
Country.create(name: "Slovakia (Slovak Republic)")
Country.create(name: "Slovenia")
Country.create(name: "Solomon Islands")
Country.create(name: "Somalia")
Country.create(name: "South Africa")
Country.create(name: "South Sudan")
Country.create(name: "Spain")
Country.create(name: "Sri Lanka")
Country.create(name: "Sudan")
Country.create(name: "Suriname")
Country.create(name: "Swaziland (Eswatini)")
Country.create(name: "Sweden")
Country.create(name: "Switzerland")
Country.create(name: "Syria, Syrian Arab Republic")
Country.create(name: "Taiwan (Republic of China)")
Country.create(name: "Tajikistan")
Country.create(name: "Tanzania; officially the United Republic of Tanzania")
Country.create(name: "Thailand")
Country.create(name: "Tibet")
Country.create(name: "Timor-Leste (East Timor)")
Country.create(name: "Togo")
Country.create(name: "Tokelau")
Country.create(name: "Tonga")
Country.create(name: "Trinidad and Tobago")
Country.create(name: "Tunisia")
Country.create(name: "Turkey")
Country.create(name: "Turkmenistan")
Country.create(name: "Turks and Caicos Islands")
Country.create(name: "Tuvalu")
Country.create(name: "Uganda")
Country.create(name: "Ukraine")
Country.create(name: "United Arab Emirates")
Country.create(name: "United Kingdom")
Country.create(name: "United States")
Country.create(name: "Uruguay")
Country.create(name: "Uzbekistan")
Country.create(name: "Vanuatu")
Country.create(name: "Vatican City State (Holy See)")
Country.create(name: "Venezuela")
Country.create(name: "Vietnam")
Country.create(name: "Virgin Islands (British)")
Country.create(name: "Virgin Islands (U.S.)")
Country.create(name: "Wallis and Futuna Islands")
Country.create(name: "Western Sahara")
Country.create(name: "Yemen")
Country.create(name: "Zambia")
Country.create(name: "Zimbabwe")

